CREATE DATABASE IF NOT EXISTS DAWNS;

USE DAWNS;

CREATE TABLE IF NOT EXISTS Items (
  upc VARCHAR(50) NOT NULL,
  name VARCHAR(255) NOT NULL,
  units VARCHAR(50) NOT NULL,
  unit_price DECIMAL(10, 2) NOT NULL,
  manufacturer VARCHAR(255) NOT NULL,
  category VARCHAR(255) NOT NULL,
  PRIMARY KEY (upc)
);

CREATE TABLE IF NOT EXISTS Sales (
  sale_id INT NOT NULL AUTO_INCREMENT,
  upc VARCHAR(50) NOT NULL,
  quantity INT NOT NULL,
  subtotal DECIMAL(10, 2) NOT NULL,
  total DECIMAL(10, 2) NOT NULL,
  sale_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (sale_id),
  FOREIGN KEY (upc) REFERENCES items(upc)
);
